/*
 Highmaps JS v5.0.6-modified (2017-01-26)

 (c) 2009-2016 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(p){"object"===typeof module&&module.exports?module.exports=p:p(Highcharts)})(function(p){(function(h){var u=h.win.document,c=h.each,r=h.pick,g=h.inArray,k=h.isNumber,A=h.splat,n,m=function(b,a){this.init(b,a)};h.extend(m.prototype,{init:function(b,a){this.options=b;this.chartOptions=a;this.columns=b.columns||this.rowsToColumns(b.rows)||[];this.firstRowAsNames=r(b.firstRowAsNames,!0);this.decimalRegex=b.decimalPoint&&new RegExp("^(-?[0-9]+)"+b.decimalPoint+"([0-9]+)$");this.rawColumns=[];
this.columns.length?this.dataFound():(this.parseCSV(),this.parseTable(),this.parseGoogleSpreadsheet())},getColumnDistribution:function(){var b=this.chartOptions,a=this.options,d=[],t=function(a){return(h.seriesTypes[a||"line"].prototype.pointArrayMap||[0]).length},f=b&&b.chart&&b.chart.type,e=[],g=[],v=0,l;c(b&&b.series||[],function(a){e.push(t(a.type||f))});c(a&&a.seriesMapping||[],function(a){d.push(a.x||0)});0===d.length&&d.push(0);c(a&&a.seriesMapping||[],function(a){var d=new n,c,w=e[v]||t(f),
k=h.seriesTypes[((b&&b.series||[])[v]||{}).type||f||"line"].prototype.pointArrayMap||["y"];d.addColumnReader(a.x,"x");for(c in a)a.hasOwnProperty(c)&&"x"!==c&&d.addColumnReader(a[c],c);for(l=0;l<w;l++)d.hasReader(k[l])||d.addColumnReader(void 0,k[l]);g.push(d);v++});a=h.seriesTypes[f||"line"].prototype.pointArrayMap;void 0===a&&(a=["y"]);this.valueCount={global:t(f),xColumns:d,individual:e,seriesBuilders:g,globalPointArrayMap:a}},dataFound:function(){this.options.switchRowsAndColumns&&(this.columns=
this.rowsToColumns(this.columns));this.getColumnDistribution();this.parseTypes();!1!==this.parsed()&&this.complete()},parseCSV:function(){var b=this,a=this.options,d=a.csv,t=this.columns,f=a.startRow||0,e=a.endRow||Number.MAX_VALUE,g=a.startColumn||0,k=a.endColumn||Number.MAX_VALUE,l,h,z=0;d&&(h=d.replace(/\r\n/g,"\n").replace(/\r/g,"\n").split(a.lineDelimiter||"\n"),l=a.itemDelimiter||(-1!==d.indexOf("\t")?"\t":","),c(h,function(a,d){var w=b.trim(a),h=0===w.indexOf("#");d>=f&&d<=e&&!h&&""!==w&&(a=
a.split(l),c(a,function(a,b){b>=g&&b<=k&&(t[b-g]||(t[b-g]=[]),t[b-g][z]=a)}),z+=1)}),this.dataFound())},parseTable:function(){var b=this.options,a=b.table,d=this.columns,t=b.startRow||0,f=b.endRow||Number.MAX_VALUE,e=b.startColumn||0,g=b.endColumn||Number.MAX_VALUE;a&&("string"===typeof a&&(a=u.getElementById(a)),c(a.getElementsByTagName("tr"),function(a,b){b>=t&&b<=f&&c(a.children,function(a,f){("TD"===a.tagName||"TH"===a.tagName)&&f>=e&&f<=g&&(d[f-e]||(d[f-e]=[]),d[f-e][b-t]=a.innerHTML)})}),this.dataFound())},
parseGoogleSpreadsheet:function(){var b=this,a=this.options,d=a.googleSpreadsheetKey,t=this.columns,f=a.startRow||0,e=a.endRow||Number.MAX_VALUE,g=a.startColumn||0,h=a.endColumn||Number.MAX_VALUE,l,k;d&&jQuery.ajax({dataType:"json",url:"https://spreadsheets.google.com/feeds/cells/"+d+"/"+(a.googleSpreadsheetWorksheet||"od6")+"/public/values?alt\x3djson-in-script\x26callback\x3d?",error:a.error,success:function(a){a=a.feed.entry;var d,w=a.length,m=0,v=0,q;for(q=0;q<w;q++)d=a[q],m=Math.max(m,d.gs$cell.col),
v=Math.max(v,d.gs$cell.row);for(q=0;q<m;q++)q>=g&&q<=h&&(t[q-g]=[],t[q-g].length=Math.min(v,e-f));for(q=0;q<w;q++)d=a[q],l=d.gs$cell.row-1,k=d.gs$cell.col-1,k>=g&&k<=h&&l>=f&&l<=e&&(t[k-g][l-f]=d.content.$t);c(t,function(a){for(q=0;q<a.length;q++)void 0===a[q]&&(a[q]=null)});b.dataFound()}})},trim:function(b,a){"string"===typeof b&&(b=b.replace(/^\s+|\s+$/g,""),a&&/^[0-9\s]+$/.test(b)&&(b=b.replace(/\s/g,"")),this.decimalRegex&&(b=b.replace(this.decimalRegex,"$1.$2")));return b},parseTypes:function(){for(var b=
this.columns,a=b.length;a--;)this.parseColumn(b[a],a)},parseColumn:function(b,a){var d=this.rawColumns,c=this.columns,f=b.length,e,h,m,l,r=this.firstRowAsNames,n=-1!==g(a,this.valueCount.xColumns),u=[],p=this.chartOptions,x,y=(this.options.columnTypes||[])[a],p=n&&(p&&p.xAxis&&"category"===A(p.xAxis)[0].type||"string"===y);for(d[a]||(d[a]=[]);f--;)e=u[f]||b[f],m=this.trim(e),l=this.trim(e,!0),h=parseFloat(l),void 0===d[a][f]&&(d[a][f]=m),p||0===f&&r?b[f]=m:+l===h?(b[f]=h,31536E6<h&&"float"!==y?b.isDatetime=
!0:b.isNumeric=!0,void 0!==b[f+1]&&(x=h>b[f+1])):(h=this.parseDate(e),n&&k(h)&&"float"!==y?(u[f]=e,b[f]=h,b.isDatetime=!0,void 0!==b[f+1]&&(e=h>b[f+1],e!==x&&void 0!==x&&(this.alternativeFormat?(this.dateFormat=this.alternativeFormat,f=b.length,this.alternativeFormat=this.dateFormats[this.dateFormat].alternative):b.unsorted=!0),x=e)):(b[f]=""===m?null:m,0!==f&&(b.isDatetime||b.isNumeric)&&(b.mixed=!0)));n&&b.mixed&&(c[a]=d[a]);if(n&&x&&this.options.sort)for(a=0;a<c.length;a++)c[a].reverse(),r&&c[a].unshift(c[a].pop())},
dateFormats:{"YYYY-mm-dd":{regex:/^([0-9]{4})[\-\/\.]([0-9]{2})[\-\/\.]([0-9]{2})$/,parser:function(b){return Date.UTC(+b[1],b[2]-1,+b[3])}},"dd/mm/YYYY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{4})$/,parser:function(b){return Date.UTC(+b[3],b[2]-1,+b[1])},alternative:"mm/dd/YYYY"},"mm/dd/YYYY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{4})$/,parser:function(b){return Date.UTC(+b[3],b[1]-1,+b[2])}},"dd/mm/YY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{2})$/,
parser:function(b){return Date.UTC(+b[3]+2E3,b[2]-1,+b[1])},alternative:"mm/dd/YY"},"mm/dd/YY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{2})$/,parser:function(b){return Date.UTC(+b[3]+2E3,b[1]-1,+b[2])}}},parseDate:function(b){var a=this.options.parseDate,d,c,f=this.options.dateFormat||this.dateFormat,e;if(a)d=a(b);else if("string"===typeof b){if(f)a=this.dateFormats[f],(e=b.match(a.regex))&&(d=a.parser(e));else for(c in this.dateFormats)if(a=this.dateFormats[c],e=b.match(a.regex)){this.dateFormat=
c;this.alternativeFormat=a.alternative;d=a.parser(e);break}e||(e=Date.parse(b),"object"===typeof e&&null!==e&&e.getTime?d=e.getTime()-6E4*e.getTimezoneOffset():k(e)&&(d=e-6E4*(new Date(e)).getTimezoneOffset()))}return d},rowsToColumns:function(b){var a,d,c,f,e;if(b)for(e=[],d=b.length,a=0;a<d;a++)for(f=b[a].length,c=0;c<f;c++)e[c]||(e[c]=[]),e[c][a]=b[a][c];return e},parsed:function(){if(this.options.parsed)return this.options.parsed.call(this,this.columns)},getFreeIndexes:function(b,a){var d,c=[],
f=[],e;for(d=0;d<b;d+=1)c.push(!0);for(b=0;b<a.length;b+=1)for(e=a[b].getReferencedColumnIndexes(),d=0;d<e.length;d+=1)c[e[d]]=!1;for(d=0;d<c.length;d+=1)c[d]&&f.push(d);return f},complete:function(){var b=this.columns,a,d=this.options,c,f,e,h,k=[],l;if(d.complete||d.afterComplete){for(e=0;e<b.length;e++)this.firstRowAsNames&&(b[e].name=b[e].shift());c=[];f=this.getFreeIndexes(b.length,this.valueCount.seriesBuilders);for(e=0;e<this.valueCount.seriesBuilders.length;e++)l=this.valueCount.seriesBuilders[e],
l.populateColumns(f)&&k.push(l);for(;0<f.length;){l=new n;l.addColumnReader(0,"x");e=g(0,f);-1!==e&&f.splice(e,1);for(e=0;e<this.valueCount.global;e++)l.addColumnReader(void 0,this.valueCount.globalPointArrayMap[e]);l.populateColumns(f)&&k.push(l)}0<k.length&&0<k[0].readers.length&&(l=b[k[0].readers[0].columnIndex],void 0!==l&&(l.isDatetime?a="datetime":l.isNumeric||(a="category")));if("category"===a)for(e=0;e<k.length;e++)for(l=k[e],f=0;f<l.readers.length;f++)"x"===l.readers[f].configName&&(l.readers[f].configName=
"name");for(e=0;e<k.length;e++){l=k[e];f=[];for(h=0;h<b[0].length;h++)f[h]=l.read(b,h);c[e]={data:f};l.name&&(c[e].name=l.name);"category"===a&&(c[e].turboThreshold=0)}b={series:c};a&&(b.xAxis={type:a},"category"===a&&(b.xAxis.uniqueNames=!1));d.complete&&d.complete(b);d.afterComplete&&d.afterComplete(b)}}});h.Data=m;h.data=function(b,a){return new m(b,a)};h.wrap(h.Chart.prototype,"init",function(b,a,d){var c=this;a&&a.data?h.data(h.extend(a.data,{afterComplete:function(f){var e,g;if(a.hasOwnProperty("series"))if("object"===
typeof a.series)for(e=Math.max(a.series.length,f.series.length);e--;)g=a.series[e]||{},a.series[e]=h.merge(g,f.series[e]);else delete a.series;a=h.merge(f,a);b.call(c,a,d)}}),a):b.call(c,a,d)});n=function(){this.readers=[];this.pointIsArray=!0};n.prototype.populateColumns=function(b){var a=!0;c(this.readers,function(a){void 0===a.columnIndex&&(a.columnIndex=b.shift())});c(this.readers,function(b){void 0===b.columnIndex&&(a=!1)});return a};n.prototype.read=function(b,a){var d=this.pointIsArray,g=d?
[]:{},f;c(this.readers,function(c){var e=b[c.columnIndex][a];d?g.push(e):g[c.configName]=e});void 0===this.name&&2<=this.readers.length&&(f=this.getReferencedColumnIndexes(),2<=f.length&&(f.shift(),f.sort(),this.name=b[f.shift()].name));return g};n.prototype.addColumnReader=function(b,a){this.readers.push({columnIndex:b,configName:a});"x"!==a&&"y"!==a&&void 0!==a&&(this.pointIsArray=!1)};n.prototype.getReferencedColumnIndexes=function(){var b,a=[],d;for(b=0;b<this.readers.length;b+=1)d=this.readers[b],
void 0!==d.columnIndex&&a.push(d.columnIndex);return a};n.prototype.hasReader=function(b){var a,d;for(a=0;a<this.readers.length;a+=1)if(d=this.readers[a],d.configName===b)return!0}})(p);(function(h){var u=h.each;h.wrap(h.Data.prototype,"init",function(c,h){c.call(this,h);h.svg&&this.loadSVG()});h.extend(h.Data.prototype,{pathToArray:function(c,h){var g=0,k=0,r,n,m=[0,0],b=[0,0],a,d,t=function(a,b){return[b.a*a[0]+b.c*a[1]+b.e,b.b*a[0]+b.d*a[1]+b.f]};c=c.replace(/[0-9]+e-?[0-9]+/g,function(a){return+a}).replace(/([A-Za-z])/g,
" $1 ").replace(/-/g," -").replace(/^\s*/,"").replace(/\s*$/,"").replace(/\s+/g," ").split(/[ ,]+/);if(1===c.length)return[];for(g=0;g<c.length;g++)if(r=/[a-zA-Z]/.test(c[g])){d=c[g];n=2;if("c"===d||"C"===d)n=6;"m"===d?b=[parseFloat(c[g+1])+b[0],parseFloat(c[g+2])+b[1]]:"M"===d&&(b=[parseFloat(c[g+1]),parseFloat(c[g+2])]);if("m"===d||"l"===d||"c"===d)c[g]=d.toUpperCase(),a=!0;else if("M"===d||"L"===d||"C"===d)a=!1;else if("h"===d)a=!0,c[g]="L",c.splice(g+2,0,0);else if("v"===d)a=!0,c[g]="L",c.splice(g+
1,0,0);else if("s"===d)a=!0,c[g]="L",c.splice(g+1,2);else if("S"===d)a=!1,c[g]="L",c.splice(g+1,2);else if("H"===d||"h"===d)a=!1,c[g]="L",c.splice(g+2,0,m[1]);else if("V"===d||"v"===d)a=!1,c[g]="L",c.splice(g+1,0,m[0]);else if("z"===d||"Z"===d)m=b}else c[g]=parseFloat(c[g]),a&&(c[g]+=m[k%2]),1===k%2&&h&&(!a||"m"===d&&3>g)&&(r=t([c[g-1],c[g]],h),c[g-1]=r[0],c[g]=r[1]),k===n-1?(m=[c[g-1],c[g]],k=0):k+=1;"number"===typeof c[0]&&4<=c.length&&(c.unshift("M"),c.splice(3,0,"L"));return c},pathToString:function(c){u(c,
function(c){var g=c.path,g=g.join(","),g=g.replace(/,?([a-zA-Z]),?/g,"$1");c.path=g});return c},roundPaths:function(c,r){var g=h.seriesTypes.map.prototype,k,p;k={xAxis:{translate:h.Axis.prototype.translate,options:{},minPixelPadding:0},yAxis:{translate:h.Axis.prototype.translate,options:{},minPixelPadding:0}};g.getBox.call(k,c);p=Math.max(k.maxX-k.minX,k.maxY-k.minY);r=r||1E3;p=r/p;k.xAxis.transA=k.yAxis.transA=p;k.xAxis.len=k.yAxis.len=r;k.xAxis.min=k.minX;k.yAxis.min=(k.minY+r)/p;u(c,function(c){var h,
b;c.path=b=g.translatePath.call(k,c.path,!0);for(h=b.length;h--;)"number"===typeof b[h]&&(b[h]=Math.round(b[h]));delete c._foundBox});return c},loadSVG:function(){function c(a){return Array.prototype.slice.call(a.getElementsByTagName("path")).concat(Array.prototype.slice.call(a.getElementsByTagName("polygon"))).concat(Array.prototype.slice.call(a.getElementsByTagName("rect")))}function h(a){if("path"===a.nodeName)return a.getAttribute("d");if("polygon"===a.nodeName)return a.getAttribute("points");
if("rect"===a.nodeName){var b=+a.getAttribute("x"),c=+a.getAttribute("y"),f=+a.getAttribute("width");a=+a.getAttribute("height");return[b,c,b+f,c,b+f,c+a,b,c+a,b,c].join(" ")}}function g(a){a=a.getCTM();if(!isNaN(a.f))return a}function k(a){var b=a.getElementsByTagName("desc");return(b=b[0]&&b[0].getElementsByTagName("name"))&&b[0]&&b[0].innerText||a.getAttribute("inkscape:label")||a.getAttribute("id")||a.getAttribute("class")}function p(a){return!/fill[\s]?\:[\s]?none/.test(a.getAttribute("style"))&&
"none"!==a.getAttribute("fill")}function n(a){var d=[],n,f,e,r,v;m.$frame=m.$frame||$("\x3cdiv\x3e").css({position:"absolute",top:"-9999em"}).appendTo($(document.body));m.$frame.html(a);a=$("svg",m.$frame)[0];a.removeAttribute("viewBox");f=c(a);u(["defs","clipPath"],function(b){u(a.getElementsByTagName(b),function(a){u(a.getElementsByTagName("path"),function(a){a.skip=!0})})});u(f,function(a,b){if(!a.skip){var c=[];0<b&&a.parentNode!==n&&(v=!0);for(n=a.parentNode;a;)c.push(a),a=a.parentNode;c.reverse();
if(e)for(a=0;a<e.length;a++)e[a]!==c[a]&&(e=e.slice(0,a));else e=c}});r=e[e.length-1];v&&u(r.getElementsByTagName("g"),function(a){var b=[],e;u(c(a),function(a){a.skip||(b=b.concat(m.pathToArray(h(a),g(a))),p(a)&&(e=!0),a.skip=!0)});d.push({name:k(a),path:b,hasFill:e})});u(f,function(a){a.skip||d.push({name:k(a),path:m.pathToArray(h(a),g(a)),hasFill:p(a)})});m.roundPaths(d);b.complete({series:[{data:d}]})}var m=this,b=this.options;-1!==b.svg.indexOf("\x3csvg")?n(b.svg):jQuery.ajax({url:b.svg,dataType:"text",
success:n})}})})(p)});